name: MovieFlix Data Extraction

on:
#  schedule:
#    - cron: '0 0 * * 0' # Roda todo domingo à meia-noite
 workflow_dispatch:      # Permite rodar manualmente pelo botão no GitHub

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout do código
         uses: actions/checkout@v4

       - name: Configurar Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'

       - name: Instalar dependências
         run: |
           pip install -r requirements.txt

       - name: Executar Script de Extração
         env:
           # Usaremos um "Secret" para proteger sua chave da API
           OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
         run: python extract-pipeline.py

       - name: Salvar CSVs como Artefatos
         uses: actions/upload-artifact@v4
         with:
           name: movieflix-data
           path: |
             movies.csv
             users.csv
             ratings.csv
